#
#Sat Apr 18 22:54:25 ECT 2026
goog\:chromeOptions={args\=[remote-allow-origins\=*], extensions\=[], prefs\={credentials_enable_service\=false, profile.password_manager_enabled\=false, profile.password_manager_leak_detection\=false}}
acceptInsecureCerts=false
browserName=chrome
